{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  jdbc-url: {{ required "secret.jdbcUrl is required" .Values.secret.jdbcUrl | quote }}
  username: {{ required "secret.username is required" .Values.secret.username | quote }}
  password: {{ required "secret.password is required" .Values.secret.password | quote }}
{{- end }}
